[project]
name = "ao3-ficsdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4",
    "matplotlib>=3.10.3",
    "requests>=2.32.4",
]
